swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Profile API
      description: API for fetching a user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions Successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{transactionId}:
      delete:
          tags:
            - Transaction Module
          summary: Deletes a transaction
          description: delete a transaction
          operationId: deleteTransaction
          parameters:
            - name: api_key
              in: header
              description: ''
              required: false
            - name: transactionId
              in: path
              description: Identifiant de la transaction à supprimer
              required: true
              type: integer
              format: int64
          responses:
            '400':
              description: Invalid Transaction value
      put:
        tags:
          - Transaction Module
        summary: transaction note API
        description: API for updating a transaction note
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description: Update user profile attributes
            required: true
            schema:
              $ref: '#/definitions/UpdateTransactionNote'
        produces:
          - application/json
        responses:
          '200':
            description: User profile retrieved successully
            schema:
              $ref: '#/definitions/UpdateTransactionNote'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: integer
        body:
          type: object
          properties:
            idItem:
              type: number
            balance:
              type: number
            date:
              type: string
            description:
              type: string
            amout:
              type: number
            transaction:
              type: string
            category:
              type: string
            notes: 
              type: string 
  UpdateTransactionNote:
    type: object
    properties:
      transactionId:
        type: integer
      body:
        type: object
        properties:
          notes:
            type: string
  TransactionNote:
    type: object
    properties:
      notes:
        type : string
 
